specVersion: 0.2.0
name: amm-subql
version: 1.0.0
description: Subql Server for indexing amm swap, lp and token creation events
repository: git@github.com:parallel-finance/amm-subql.git
schema:
  file: ./schema.graphql
network:
  endpoint: wss://heiko-rpc.parallel.fi
  # endpoint: wss://parallel-heiko.api.onfinality.io/public-ws
  genesisHash: '0x64a1c658a48b2e70a7fb1ad4c39eea35022568c20fc44a6e2e3d0a57aee6053b'
dataSources:
  - kind: substrate/Runtime
    startBlock: 800000
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: amm
