specVersion: 0.2.0
name: amm-subql
version: 1.0.0
description: Subql Server for indexing amm swap, lp and token creation events
repository: git@github.com:parallel-finance/amm-subql.git
schema:
  file: ./schema.graphql
network:
  endpoint: wss://regnet-rpc.parallel.fi
  genesisHash: '0xc26cd1cc96b5937b5451699b536182aac49dcf2c3b152b0fd55bbaa017640469'
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleTokenCreate
          kind: substrate/EventHandler
          filter: 
            module: assets
            method: ForceCreated
        - handler: handleTokenMeta
          kind: substrate/EventHandler
          filter: 
            module: assets
            method: MetadataSet
        - handler: handlePoolCreate
          kind: substrate/EventHandler
          filter: 
            module: amm
            method: PoolCreated
        - handler: handlePoolAddLiquidity
          kind: substrate/EventHandler
          filter: 
            module: amm
            method: LiquidityAdded
        - handler: handlePoolRemoveLiquidity
          kind: substrate/EventHandler
          filter: 
            module: amm
            method: LiquidityRemoved
        - handler: handleAmmTrade
          kind: substrate/EventHandler
          filter: 
            module: amm
            method: Traded
            
            
