specVersion: 0.2.0
name: amm-subql
version: 1.0.0
description: Subql Server for indexing amm swap, lp and token creation events
repository: git@github.com:parallel-finance/amm-subql.git
schema:
  file: ./schema.graphql
network:
  endpoint: wss://regnet-rpc.parallel.fi
  genesisHash: ''
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleTokenCreate
          kind: substrate/EventHandler
          filter: 
            module: assets
            method: forceCreate
        - handler: handleTokenMeta
          kind: substrate/EventHandler
          filter: 
            module: assets
            method: forceSetMetadata
        - handler: handlePoolCreate
          kind: substrate/EventHandler
          filter: 
            module: amm
            method: createPool
        - handler: handlePoolAddLiquidity
          kind: substrate/EventHandler
          filter: 
            module: amm
            method: addLiquidity
        - handler: handlePoolRemoveLiquidity
          kind: substrate/EventHandler
          filter: 
            module: amm
            method: removeLiquidity
        - handler: handleAmmTrade
          kind: substrate/EventHandler
          filter: 
            module: ammRoute
            method: trade
            
            
