specVersion: 0.2.0
name: amm-subql
version: 1.0.0
description: Subql Server for indexing amm swap, lp and token creation events
repository: git@github.com:parallel-finance/amm-subql.git
schema:
  file: ./schema.graphql
network:
  endpoint: wss://regnet3-rpc.parallel.fi
  genesisHash: '0xdcbab0fce9d8e692ebe65ad983c7b62199f7e0b3cf6e657edf63240601d73857'
dataSources:
  - kind: substrate/Runtime
    startBlock: 8676
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: amm
